spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book-service
    username: postgres
    password: longthanh04
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # Hoặc create-drop nếu muốn xoá và tạo lại mỗi lần chạy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: book-service

server:
  port: 8081
